apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: k8sible

helmCharts:
  - name: k8sible
    repo: oci://ghcr.io/bensonphillipsiv/charts
    version: latest
    releaseName: k8sible
