apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: node-red

resources:
  - ingress.yaml

helmCharts:
  - name: node-red
    repo: https://schwarzit.github.io/node-red-chart
    version: 0.40.0
    releaseName: node-red
    valuesInline:
      env:
        - name: TZ
          value: America/Chicago
      persistence:
        enabled: true
        size: 1Gi

patches:
  - target:
      kind: Service
      name: node-red
    patch: |
      - op: replace
        path: /spec/type
        value: LoadBalancer
      - op: add
        path: /spec/loadBalancerIP
        value: 192.168.1.115
      - op: add
        path: /spec/externalTrafficPolicy
        value: Cluster
