---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-gpt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-gpt
  template:
    metadata:
      labels:
        app: home-gpt
    spec:
      containers:
      - name: home-gpt
        image: ghcr.io/bensonphillipsiv/homegpt:latest
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: home-gpt
          - secretRef:
              name: home-gpt
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values: ["b1"]
---
apiVersion: v1
kind: Service
metadata:
  name: home-gpt
  labels:
    app: home-gpt
spec:
  type: ClusterIP
  ports:
    - port: 8765
      targetPort: 8765
      protocol: TCP
      name: websocket
  selector:
    app: home-gpt