---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-gpt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-gpt
  template:
    metadata:
      labels:
        app: home-gpt
    spec:
      containers:
      - name: home-gpt
        image: ghcr.io/bensonphillipsiv/homegpt:latest
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: home-gpt
          - secretRef:
              name: home-gpt
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values: ["b1"]
---
apiVersion: v1
kind: Service
metadata:
  name: home-gpt
  labels:
    app: home-gpt
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  loadBalancerIP: 192.168.1.121
  sessionAffinity: None
  ports:
    - name: mic
      port: 4712
      targetPort: 4712
      protocol: TCP
    - name: speaker
      port: 4713
      targetPort: 4713
      protocol: TCP
---
